-- MySQL Script generated by MySQL Workbench
-- Mon Jan 11 11:18:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- (Pablo) Añadido y conecta a la base de datos
ALTER USER 'root'@'localhost' IDENTIFIED BY 'mysql';

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cpwdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cpwdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cpwdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `cpwdb` ;

-- -----------------------------------------------------
-- Table `cpwdb`.`data_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpwdb`.`data_sessions` (
  `iddata_sessions` INT NOT NULL AUTO_INCREMENT,
  `idSesion` INT NULL DEFAULT NULL,
  `Date` INT NULL DEFAULT NULL,
  `left_knee_goal` FLOAT NULL DEFAULT NULL,
  `left_knee` FLOAT NULL DEFAULT NULL,
  `left_knee_force` FLOAT NULL DEFAULT NULL,
  `right_knee_goal` FLOAT NULL DEFAULT NULL,
  `right_knee` FLOAT NULL DEFAULT NULL,
  `right_knee_force` FLOAT NULL DEFAULT NULL,
  `left_hip_goal` FLOAT NULL DEFAULT NULL,
  `left_hip` FLOAT NULL DEFAULT NULL,
  `left_hip_force` FLOAT NULL DEFAULT NULL,
  `right_hip_goal` FLOAT NULL DEFAULT NULL,
  `right_hip` FLOAT NULL DEFAULT NULL,
  `right_hip_force` FLOAT NULL DEFAULT NULL,
  `weight_gauge` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`iddata_sessions`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `cpwdb`.`tabla_pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpwdb`.`tabla_pacientes` (
  `idtabla_pacientes` INT NOT NULL AUTO_INCREMENT,
  `NombrePaciente` VARCHAR(45) NULL DEFAULT NULL,
  `ApellidoPaciente` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtabla_pacientes`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `cpwdb`.`tabla_sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpwdb`.`tabla_sesion` (
  `idtable_session` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `idPaciente` INT NULL DEFAULT NULL,
  `NumberSession` INT NULL DEFAULT NULL,
  `idTerapeuta` INT NULL DEFAULT NULL,
  `patiente_age` INT NULL DEFAULT NULL,
  `patiente_weight` INT NULL DEFAULT NULL,
  `leg_length` INT NULL DEFAULT NULL,
  `hip_upper_strap` INT NULL DEFAULT NULL,
  `knee_lower_strap` INT NULL DEFAULT NULL,
  `gait_velocity` INT NULL DEFAULT NULL,
  `gmfcs` VARCHAR(45) NULL DEFAULT NULL,
  `steps` INT NULL DEFAULT NULL,
  `ROM` INT NULL DEFAULT NULL,
  `PBWS` INT NULL DEFAULT NULL,
  `control_mode` VARCHAR(45) NULL DEFAULT NULL,
  `right_knee_config` VARCHAR(45) NULL DEFAULT NULL,
  `left_knee_config` VARCHAR(45) NULL DEFAULT NULL,
  `right_hip_config` VARCHAR(45) NULL DEFAULT NULL,
  `left_hip_config` VARCHAR(45) NULL DEFAULT NULL,
  `observations` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtable_session`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `cpwdb`.`tabla_terapeutas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpwdb`.`tabla_terapeutas` (
  `idtabla_terapeutas` INT NOT NULL AUTO_INCREMENT,
  `NombreTerapeuta` VARCHAR(45) NULL DEFAULT NULL,
  `ApellidoTerapeuta` VARCHAR(45) NULL DEFAULT NULL,
  `Centro` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtabla_terapeutas`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
